### PR TITLE
[TASK] Add dev and no dev installation options for composer

### PR DESCRIPTION
**Pull request by MattiasNilsson**

### CODE REVIEW

**Comment by jozefspisiak** [comment]
Shouldn't we add latest dev on all our extensions? Like t3kit_extension_tools, pxa_form_enhancement and pxa_newsletter_subscription?

**Comment by jozefspisiak** [comment]
also what is with the plan to move the docker repo to our?

**Comment by MattiasNilsson** [comment]
I agree on this and will do that

> Shouldn't we add latest dev on all our extensions? Like t3kit_extension_tools, pxa_form_enhancement and pxa_newsletter_subscription?

With this i am not sure what you mean? 

> also what is with the plan to move the docker repo to our?

**Comment by jozefspisiak** [comment]
lauri/dockert3kit vs t3kit/t3kit_docker

**Comment by jozefspisiak** [comment]
Looks good to me. @dmh : Dmytro can we merge this?

**Review by dmh — COMMENTED** [review]
Wow, this is great. Didn't know about this possibility to install package through composer with keeping git functionality.
But I noticed that with composer **dev** we will get `theme_t3kit` or `theme_t3kit_bluemountain` without `felayout` as a submodule, so we need to install it manually `git submodule update --init`, or we need to add some additional config to clone it automatically.

Also I got troubles with **static_info_tables** extension. So I needed to add it to our `composer.json` file. Could you check is it only my problem, or we really should add it (static_info_tables) to our composer file?
`"static_info_tables": ">=6.3.0 <=6.3.99"`

**Comment by MattiasNilsson** [comment]
To solve the problem of felayout we should apply them as dependencies in the themes_\* repos then composer will fix it for us.

When it comes to static info tables I can´t reproduce the problem?

**Comment by MattiasNilsson** [comment]
@dmh You still have the same issue?

**Pull request merged**
