### PR TITLE
[FEATURE] Solution for editors to add redirects

### PR DESCRIPTION
**Pull request by Chanpiseth09**

### CODE REVIEW

**Comment by Chanpiseth09** [comment]
Hi @jozefspisiak

Please review my changing.

Thanks,
Chanpiseth

**Comment by MattiasNilsson** [comment]
This looks good to me! 👍

**Comment by manmath** [comment]
@jozefspisiak  and @MattiasNilsson Please review and merge or feedback for this pull request.

**Comment by Chanpiseth09** [comment]
@jozefspisiak Please review and merge the code or give feedback!

**Comment by laurisaarni** [comment]
@Chanpiseth09 please resolve conflicts.

**Comment by Chanpiseth09** [comment]
@laurisaarni @manmath  i have resolved conflicts already

**Comment by manmath** [comment]
@MattiasNilsson It looks good and it is ready for you to review and merge.

**Comment by MattiasNilsson** [comment]
@manmath There is still a conflict in the composer.json

**Comment by Chanpiseth09** [comment]
@MattiasNilsson I have resolved conflict already.

**Comment by MattiasNilsson** [comment]
Great! 👍

**Pull request merged**
